name: Secure CI / CD

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "Current folder: $PWD"
          echo "Files in folder:"
          ls -l "$PWD"
          echo "Dockerfile content:"
          cat "$PWD/Dockerfile"

      - name: Set up QEMU (for buildx)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Build Docker image (local tag)
        id: build-image
        run: |
          IMAGE_NAME="secure-app"
          IMAGE_TAG="ghcr.io/${GITHUB_REPOSITORY_OWNER}/$IMAGE_NAME:${GITHUB_SHA}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "Building image with tag: $IMAGE_TAG"
          docker build -f "$PWD/Dockerfile" -t "$IMAGE_TAG" "$PWD"

      - name: Run SCA + image scan with Trivy
        id: trivy-scan
        run: |
          IMAGE_TAG=${{ steps.build-image.outputs.IMAGE_TAG }}
          trivy fs --exit-code 0 --format json --output trivy_fs.json .
          trivy image --format json --output trivy_image.json --exit-code 1 --severity CRITICAL "$IMAGE_TAG" || echo "TRIVY_CRITICAL=1" >> $GITHUB_OUTPUT

      - name: Run SAST with Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'

      - name: Generate SBOM with Syft
        id: sbom
        run: |
          IMAGE_TAG=${{ steps.build-image.outputs.IMAGE_TAG }}
          syft "$IMAGE_TAG" -o cyclonedx-json=sbom.cyclonedx.json
          echo "SBOM_FILE=sbom.cyclonedx.json" >> $GITHUB_OUTPUT

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cyclonedx.json

      - name: Evaluate scan results and fail on policy
        run: |
          if grep -R "GPL-2.0" -n package* requirements* package-lock.json 2>/dev/null; then
            echo "Disallowed license detected (GPL-2.0)" >&2
            exit 2
          fi
          echo "No blocking policy violations found."

  release:
    needs: build-and-scan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "Current folder: $PWD"
          echo "Files in folder:"
          ls -l "$PWD"
          echo "Dockerfile content:"
          cat "$PWD/Dockerfile"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image for release
        id: release-image
        run: |
          IMAGE_NAME="secure-app"
          IMAGE_TAG="ghcr.io/${GITHUB_REPOSITORY_OWNER}/$IMAGE_NAME:latest"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "Building release image with tag: $IMAGE_TAG"
          docker build -f "$PWD/Dockerfile" -t "$IMAGE_TAG" "$PWD"

      - name: Decode cosign key
        id: cosign-key
        run: |
          echo "${{ secrets.COSIGN_KEY_B64 }}" | base64 --decode > cosign.key

      - name: Sign Docker image with Cosign
        run: |
          IMAGE_TAG=${{ steps.release-image.outputs.IMAGE_TAG }}
          cosign sign --key cosign.key "$IMAGE_TAG"

      - name: Push Docker image to GHCR
        run: |
          IMAGE_TAG=${{ steps.release-image.outputs.IMAGE_TAG }}
          docker push "$IMAGE_TAG"

      - name: Verify image signature
        run: |
          IMAGE_TAG=${{ steps.release-image.outputs.IMAGE_TAG }}
          cosign verify --key cosign.key.pub "$IMAGE_TAG" || true
